### ISSUE TITLE
FATAL Exception Crash When running listview example

### ISSUE THREAD

**Issue by SairamRachapudi** [jwplayer/jwplayer-android-best-practice-apps#12]
##  This crash happens when user play multiple streams in listview.

**com.jwplayer.demo.listview E/AndroidRuntime: FATAL EXCEPTION: main**
                                                                            **Process: com.jwplayer.demo.listview, PID: 11051
                                                                            java.util.ConcurrentModificationException**
                                                                                at java.util.ArrayList$Itr.next(ArrayList.java:831)
                                                                                at com.longtailvideo.jwplayer.core.c.d.a(SourceFile:215)
                                                                                at com.longtailvideo.jwplayer.core.d.c.onPageFinished(SourceFile:101)
                                                                                at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:196)
                                                                                at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:70)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by GMSyrimis** [comment]
Closing this issue as we have new demos in this repo that shows how to manage players in a ListView or RecyclerView
