### ISSUE TITLE
android.view.InflateException on 360 video sample

### ISSUE THREAD

**Issue by mrithun-cgvak** [jwplayer/jwplayer-android-best-practice-apps#13]
FATAL EXCEPTION: main
                                                                            Process: com.jwplayer.demo.vrsample, PID: 14483
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jwplayer.demo.vrsample/com.jwplayer.demo.vrsample.VideoActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.longtailvideo.jwplayer.vr.JWVrVideoView
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                at android.os.Looper.loop(Looper.java:207)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5769)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.longtailvideo.jwplayer.vr.JWVrVideoView
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                                at com.jwplayer.demo.vrsample.VideoActivity.onCreate(VideoActivity.java:36)
                                                                                at android.app.Activity.performCreate(Activity.java:6583)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.longtailvideo.jwplayer.vr.JWVrVideoView
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                at com.jwplayer.demo.vrsample.VideoActivity.onCreate(VideoActivity.java:36) 
                                                                                at android.app.Activity.performCreate(Activity.java:6583) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                at com.jwplayer.demo.vrsample.VideoActivity.onCreate(VideoActivity.java:36) 
                                                                                at android.app.Activity.performCreate(Activity.java:6583) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                             Caused by: java.lang.NoClassDefFoundError: com.longtailvideo.jwplayer.vr.c.c
                                                                                at com.longtailvideo.jwplayer.vr.a.f.<init>(SourceFile:172)
                                                                                at com.longtailvideo.jwplayer.vr.JWVrVideoView.a(SourceFile:303)
                                                                                at com.longtailvideo.jwplayer.vr.JWVrVideoView.<init>(SourceFile:282)
                                                                                at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                at com.jwplayer.demo.vrsample.VideoActivity.onCreate(VideoActivity.java:36) 
                                                                                at android.app.Activity.performCreate(Activity.java:6583) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5769) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by GMSyrimis** [comment]
Closing this issue as it's fairly old and we no longer support 360 video
