### ISSUE TITLE
ChromcastDemo with v3 and v4 sdk on Android 13 crashes while beginning of casting with Flag issues

### ISSUE THREAD

**Issue by freny-John** [jwplayer/jwplayer-android-best-practice-apps#694]
E  FATAL EXCEPTION: main
    Process: com.jwplayer.chromecastdemo, PID: 17413
    java.lang.IllegalArgumentException: com.jwplayer.chromecastdemo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
    	at com.google.android.gms.cast.framework.media.internal.zzm.zza(com.google.android.gms:play-services-cast-framework@@19.0.0:46)
    	at com.google.android.gms.cast.framework.CastSession$zza.onResult(com.google.android.gms:play-services-cast-framework@@19.0.0:11)
    	at com.google.android.gms.common.api.internal.BasePendingResult$CallbackHandler.handleMessage(com.google.android.gms:play-services-base@@17.1.0:11)
    	at android.os.Handler.dispatchMessage(Handler.java:106)
    	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
    	at android.os.Looper.loopOnce(Looper.java:201)
    	at android.os.Looper.loop(Looper.java:288)
    	at android.app.ActivityThread.main(ActivityThread.java:7872)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

For this issue, this should be resolved with the modern version of our SDK.
