### ISSUE TITLE
Null Pointer in onControlBarVisibilityChanged

### ISSUE THREAD

**Issue by HassanImtiaz** [jwplayer/jwplayer-android-best-practice-apps#698]
Hi,

We have seen multiple reports of null pointer exceptions in onControlBarVisibilityChanged method. These crash reports are for jwplayer sdk version 4.10.1.

Here is a complete log: 

**_**Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setPadding(int, int, int, int)' on a null object reference
       at com.longtailvideo.jwplayer.player.c.onControlBarVisibilityChanged(SourceFile:800)
       at com.longtailvideo.jwplayer.f.a.a.f.a(SourceFile:1058)
       at com.longtailvideo.jwplayer.f.a.a.i.b(SourceFile:38)
       at com.longtailvideo.jwplayer.f.a.a.i.$r8$lambda$BDQ9saggYq_6Pe8X8qweGl6fyeQ()
       at com.longtailvideo.jwplayer.f.a.a.i$$ExternalSyntheticLambda0.run(:8)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)**_**

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

This should be resolved in the most recent versions of our SDK, and if not, please raise a support ticket as defined in the above link.
